"""add language to posts

Revision ID: 548875375a19
Revises: 4b60a0c4a1e5
Create Date: 2018-09-27 06:31:02.080532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '548875375a19'
down_revision = '4b60a0c4a1e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
