"""add menu table

Revision ID: 79a6147b47a8
Revises: 849f24595141
Create Date: 2018-10-27 13:01:54.963796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79a6147b47a8'
down_revision = '849f24595141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_timestamp'), 'menu', ['timestamp'], unique=False)
    op.create_table('menus',
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.Column('dish_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dish.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menus')
    op.drop_index(op.f('ix_menu_timestamp'), table_name='menu')
    op.drop_table('menu')
    # ### end Alembic commands ###
