"""add stock share table

Revision ID: b716abbf3243
Revises: ea4228fdf5fe
Create Date: 2019-07-27 16:45:47.442522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b716abbf3243'
down_revision = 'ea4228fdf5fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('buy_price', sa.Float(), nullable=True),
    sa.Column('sell_price', sa.Float(), nullable=True),
    sa.Column('buy_timestamp', sa.DateTime(), nullable=True),
    sa.Column('sell_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_share_buy_timestamp'), 'stock_share', ['buy_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_share_buy_timestamp'), table_name='stock_share')
    op.drop_table('stock_share')
    # ### end Alembic commands ###
