name: lws_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3
  - elasticsearch
  - dotenv
  - flask
  - flask-wtf
  - flask-sqlalchemy
  - flask-migrate
  - flask-login
  - flask-mail
  - flask-bootstrap
  - flask-moment
  - flask-babel
  - pymysql
  - pyjwt
  - nose
  - requests
  - pip:
    - guess_language-spirit
